spring.application.name=datingapp

spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/datingapp
spring.datasource.password=DatingApp8912

#;DB_CLOSE_DELAY=-1

#spring.datasource.url=jdbc:h2:file:./data/datingapp;MODE=PostgreSQL
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

spring.jpa.hibernate.dll-auto=update

spring.jpa.open-in-view=false

server.port=8081
server.ssl.enabled=true
server.ssl.key-store=classpath:selfsigned.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=selfsigned

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate.SQL=OFF

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

jwt.secret=D0K£s:8bz8}$3B7d1G3FK£Y0pYK2;#(I(_,`g£p!WQ='9l4c<<

#3600000
jwt.expiration-ms=3600000

jwt.refresh-expiration-ms=604800000